spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_engine
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-retries: 3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}