version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_engine_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: payment_engine

    ports:
      - "5432:5432"
    restart: unless-stopped
